export const UI = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  SHOW_NETWORK_ERROR: 'SHOW_NETWORK_ERROR',
  ERASE_NETWORK_ERROR: 'ERASE_NETWORK_ERROR'
}

export const account = {
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
  UPDATE_PROFILE_INDICATOR: 'UPDATE_PROFILE_INDICATOR',
  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
  CHANGE_PASSWORD_INDICATOR: 'CHANGE_PASSWORD_INDICATOR',
  GET_ACCOUNT_DASHBOARD_REQUEST: 'GET_ACCOUNT_DASHBOARD_REQUEST',
  GET_ACCOUNT_DASHBOARD_SUCCESS: 'GET_ACCOUNT_DASHBOARD_SUCCESS',
  GET_ACCOUNT_DASHBOARD_FAILURE: 'GET_ACCOUNT_DASHBOARD_FAILURE',
  GET_ACCOUNT_DASHBOARD_INDICATOR: 'GET_ACCOUNT_DASHBOARD_INDICATOR',
}

export const wallet = {
  GET_WALLET_REQUEST: 'GET_WALLET_REQUEST',
  GET_WALLET_SUCCESS: 'GET_WALLET_SUCCESS',
  GET_WALLET_FAILURE: 'GET_WALLET_FAILURE',
  GET_WALLET_INDICATOR: 'GET_WALLET_INDICATOR',
  GET_WALLET_HISTORY_REQUEST: 'GET_WALLET_HISTORY_REQUEST',
  GET_WALLET_HISTORY_SUCCESS: 'GET_WALLET_HISTORY_SUCCESS',
  GET_WALLET_HISTORY_FAILURE: 'GET_WALLET_HISTORY_FAILURE',
  GET_WALLET_HISTORY_INDICATOR: 'GET_WALLET_HISTORY_INDICATOR',
  INCREMENT_WALLET_HISTORY_PAGENUM: 'INCREMENT_WALLET_HISTORY_PAGENUM',
  GET_WALLET_REQUESTS: 'GET_WALLET_REQUESTS',
  GET_WALLET_REQUESTS_SUCCESS: 'GET_WALLET_REQUESTS_SUCCESS',
  GET_WALLET_REQUESTS_FAILURE: 'GET_WALLET_REQUESTS_FAILURE',
  GET_WALLET_REQUESTS_INDICATOR: 'GET_WALLET_REQUESTS_INDICATOR',
  INCREMENT_WALLET_REQUESTS_PAGENUM: 'INCREMENT_WALLET_REQUESTS_PAGENUM',
  REQUEST_WITHDRAWAL_REQUEST: 'REQUEST_WITHDRAWAL_REQUEST',
  REQUEST_WITHDRAWAL_SUCCESS: 'REQUEST_WITHDRAWAL_SUCCESS',
  REQUEST_WITHDRAWAL_FAILURE: 'REQUEST_WITHDRAWAL_FAILURE',
  REQUEST_WITHDRAWAL_INDICATOR: 'REQUEST_WITHDRAWAL_INDICATOR',
  SET_PIN_REQUEST: 'SET_PIN_REQUEST',
  SET_PIN_SUCCESS: 'SET_PIN_SUCCESS',
  SET_PIN_FAILURE: 'SET_PIN_FAILURE',
  SET_PIN_INDICATOR: 'SET_PIN_INDICATOR',
  UPDATE_BANK_INFO_REQUEST: 'UPDATE_BANK_INFO_REQUEST',
  UPDATE_BANK_INFO_SUCCESS: 'UPDATE_BANK_INFO_SUCCESS',
  UPDATE_BANK_INFO_FAILURE: 'UPDATE_BANK_INFO_FAILURE',
  UPDATE_BANK_INFO_INDICATOR: 'UPDATE_BANK_INFO_INDICATOR'
  
}

export const auth = {
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  SIGN_OUT: 'SIGN_OUT',
  CONFIRM_PIN: 'CONFIRM_PIN',
  CONFIRM_PIN_SUCCESS: 'CONFIRM_PIN_SUCCESS',
  PIN_ERROR: 'PIN_ERROR',
  ISLOADING: 'ISLOADING',
  GET_USER_PROFILE: 'GET_USER_PROFILE'
}

export const dashboard = {
  GET_USER_DASHBOARD_REQUEST: 'GET_USER_DASHBOARD_REQUEST',
  GET_USER_DASHBOARD_SUCCESS: 'GET_USER_DASHBOARD_SUCCESS',
  GET_USER_DASHBOARD_FAILURE: 'GET_USER_DASHBOARD_FAILURE'
}

export const commodity = {
  GET_COMMODITIES_REQUEST: 'GET_COMMODITIES_REQUEST',
  GET_COMMODITIES_SUCCESS: 'GET_COMMODITIES_SUCCESS',
  GET_COMMODITIES_FAILURE: 'GET_COMMODITIES_FAILURE',
  GET_RELATED_COMMODITIES: 'GET_RELATED_COMMODITIES',
  GET_RELATED_COMMODITIES_SUCCESS: 'GET_RELATED_COMMODITIES_SUCCESS',
  GET_RELATED_COMMODITIES_FAILURE: 'GET_RELATED_COMMODITIES_FAILURE',
  GET_RELATED_COMMODITIES_INDICATOR: 'GET_RELATED_COMMODITIES_INDICATOR',
  PURCHASE_COMMODITY_REQUEST: 'PURCHASE_COMMODITY_REQUEST',
  PURCHASE_COMMODITY_SUCCESS: 'PURCHASE_COMMODITY_SUCCESS',
  PURCHASE_COMMODITY_FAILURE: 'PURCHASE_COMMODITY_FAILURE',
  PURCHASE_COMMODITY_INDICATOR: 'PURCHASE_COMMODITY_INDICATOR',
  INCREMENT_PAGENUM: 'INCREMENT_PAGENUM',
  GET_SINGLE_COMMODITY_REQUEST: "GET_SINGLE_COMMODITY_REQUEST",
  GET_SINGLE_COMMODITY_SUCCESS: "GET_SINGLE_COMMODITY_SUCCESS",
  GET_SINGLE_COMMODITY_FAILURE: "GET_SINGLE_COMMODITY_FAILURE",
  GET_SINGLE_COMMODITY_INDICATOR: 'GET_SINGLE_COMMODITY_INDICATOR',
}

export const deal = {
  GET_DEALS_REQUEST: 'GET_DEALS_REQUEST',
  GET_DEALS_SUCCESS: 'GET_DEALS_SUCCESS',
  GET_DEALS_FAILURE: 'GET_DEALS_FAILURE',
  GET_DEALS_INDICATOR: 'GET_DEALS_INDICATOR',
  GET_SINGLE_DEAL_REQUEST: 'GET_SINGLE_DEAL_REQUEST',
  GET_SINGLE_DEAL_SUCCESS: 'GET_SINGLE_DEAL_SUCCESS',
  GET_SINGLE_DEAL_FAILURE: 'GET_SINGLE_DEAL_FAILURE',
}