export const UI = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING'
}

export const account = {
  
}

export const auth = {
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  CONFIRM_PIN: 'CONFIRM_PIN',
  CONFIRM_PIN_SUCCESS: 'CONFIRM_PIN_SUCCESS',
  PIN_ERROR: 'PIN_ERROR',
  ISLOADING: 'ISLOADING',
}

export const dashboard = {
  GET_USER_DASHBOARD_REQUEST: 'GET_USER_DASHBOARD_REQUEST',
  GET_USER_DASHBOARD_SUCCESS: 'GET_USER_DASHBOARD_SUCCESS',
  GET_USER_DASHBOARD_FAILURE: 'GET_USER_DASHBOARD_FAILURE'
}